export const products = [
    { name: 'Laptop Lenovo IdeaPad 3', price: 2500 },
    { name: 'Telefon Samsung Galaxy S21', price: 3500 },
    { name: 'Televizor LG Smart 4K', price: 2000 },
    { name: 'Căști Wireless Sony WH-1000XM4', price: 1200 },
    { name: 'Mouse Logitech MX Master 3', price: 400 },
    { name: 'Tastatură Mechanical Keychron K2', price: 600 },
    { name: 'Monitor Dell UltraSharp 27"', price: 1800 },
    { name: 'Tabletă Apple iPad Air', price: 3000 },
    { name: 'Smartwatch Garmin Fenix 6', price: 2500 },
    { name: 'Boxă Portabilă JBL Charge 5', price: 700 },
    { name: 'Aspirator Robot Xiaomi Mi Robot Vacuum', price: 1500 },
    { name: 'Frigider Samsung No Frost', price: 4000 },
    { name: 'Mașină de Spălat Whirlpool', price: 2500 },
    { name: 'Espressor DeLonghi Magnifica', price: 2000 },
    { name: 'Cuptor cu Microunde Samsung', price: 800 },
    { name: 'Fier de Călcat Philips PerfectCare', price: 500 },
    { name: 'Mixer de Bucătărie Bosch', price: 300 },
    { name: 'Set Oale Tefal Ingenio', price: 600 },
    { name: 'Saltea Dormeo Memory', price: 1200 },
    { name: 'Scaun Gaming DXRacer', price: 1000 },
    { name: 'Bicicletă MTB Rockrider', price: 1500 },
    { name: 'Trotinetă Electrică Xiaomi Mi Pro 2', price: 2500 },
    { name: 'Cameră Foto Canon EOS 250D', price: 3000 },
    { name: 'Dronă DJI Mini 2', price: 2500 },
    { name: 'Consolă Sony PlayStation 5', price: 3000 },
    { name: 'Joc Video FIFA 25', price: 300 },
    { name: 'Geacă de Iarnă The North Face', price: 800 },
    { name: 'Pantofi Sport Nike Air Max', price: 600 },
    { name: 'Ceas Fossil Hybrid HR', price: 900 },
    { name: 'Ochelari de Soare Ray-Ban', price: 700 },
];